export interface CommunityLesson {
  id: string
  title: string
  subject: string
  grade: string
  duration: string
  teacher: string
  school: string
  state: string
  aiConcept: string
  description: string
  tags: string[]
  uses: number
  rating: number
  verified: boolean
  date: string
}

export const COMMUNITY_LESSONS: CommunityLesson[] = [
  {
    id: "cl-1",
    title: "Bias in Facial Recognition: A History Lesson",
    subject: "Social Studies",
    grade: "9–12",
    duration: "50 min",
    teacher: "Marcus Johnson",
    school: "Lincoln High School",
    state: "CA",
    aiConcept: "Bias & fairness",
    description: "Students examine documented cases where facial recognition systems failed for certain demographic groups and trace the historical roots of bias in training data.",
    tags: ["equity", "bias", "data ethics"],
    uses: 234,
    rating: 4.8,
    verified: true,
    date: "2025-11-20",
  },
  {
    id: "cl-2",
    title: "Who Decides What's a Weed? AI in Agriculture",
    subject: "Environmental Science",
    grade: "9–12",
    duration: "45 min",
    teacher: "Priya Chandrasekaran",
    school: "Central Valley Academy",
    state: "CA",
    aiConcept: "AI in society",
    description: "Using precision-agriculture AI as a lens, students debate who gets to define the problems AI systems are built to solve — and whose knowledge gets encoded.",
    tags: ["agriculture", "equity", "AI decisions"],
    uses: 187,
    rating: 4.7,
    verified: true,
    date: "2025-12-05",
  },
  {
    id: "cl-3",
    title: "Write Like a Machine — NLP in ELA",
    subject: "English Language Arts",
    grade: "6–8",
    duration: "55 min",
    teacher: "Sofia Guzmán",
    school: "Roosevelt Middle School",
    state: "TX",
    aiConcept: "How AI works",
    description: "Students reverse-engineer how autocomplete works by building word-prediction tables from song lyrics, then reflect on AI creativity and authorship.",
    tags: ["language", "creativity", "autocomplete"],
    uses: 412,
    rating: 4.9,
    verified: true,
    date: "2025-10-14",
  },
  {
    id: "cl-4",
    title: "Redlining, Algorithms, and Neighborhood Credit Scores",
    subject: "History",
    grade: "10–12",
    duration: "60 min",
    teacher: "Deshawn Okafor",
    school: "Woodson High School",
    state: "MD",
    aiConcept: "Algorithmic impact",
    description: "Students compare 1930s HOLC redlining maps with present-day algorithmic lending scores to understand how historical discrimination can be encoded in AI systems.",
    tags: ["history", "equity", "algorithms", "housing"],
    uses: 321,
    rating: 4.8,
    verified: true,
    date: "2025-09-28",
  },
  {
    id: "cl-5",
    title: "Is a Playlist Fair? Recommendation Systems in Music",
    subject: "Math / Data Science",
    grade: "6–8",
    duration: "40 min",
    teacher: "Yuki Tanaka",
    school: "Jefferson Middle School",
    state: "WA",
    aiConcept: "Recommendation systems",
    description: "Students build a simple collaborative-filter recommendation system using a ratings matrix, then test whether the system gives different artists equal exposure.",
    tags: ["math", "data", "fairness", "music"],
    uses: 293,
    rating: 4.6,
    verified: true,
    date: "2025-11-03",
  },
  {
    id: "cl-6",
    title: "Teaching Machines to See — Computer Vision Card Sort",
    subject: "Art / Design",
    grade: "6–8",
    duration: "45 min",
    teacher: "Amara Osei",
    school: "Creative Arts Academy",
    state: "NY",
    aiConcept: "Computer vision",
    description: "Students sort photos by visual features to simulate image classifiers, then discuss why some images are consistently misclassified — and whose aesthetics are centered.",
    tags: ["vision", "art", "image classification", "culture"],
    uses: 156,
    rating: 4.5,
    verified: false,
    date: "2026-01-08",
  },
  {
    id: "cl-7",
    title: "ChatGPT vs. The Library — Research in the Age of AI",
    subject: "Library / Information Science",
    grade: "9–12",
    duration: "45 min",
    teacher: "Rebecca Novotny",
    school: "Eastview High School",
    state: "MN",
    aiConcept: "AI & information",
    description: "Students run identical research tasks on a generative AI tool and a curated database, evaluate result quality, and develop personal guidelines for when to trust each.",
    tags: ["research", "misinformation", "LLMs"],
    uses: 508,
    rating: 4.7,
    verified: true,
    date: "2025-12-19",
  },
  {
    id: "cl-8",
    title: "Training Data Scavenger Hunt",
    subject: "Science / STEM",
    grade: "6–8",
    duration: "50 min",
    teacher: "Jordan Rivera",
    school: "Maple Grove Middle",
    state: "MN",
    aiConcept: "Training data",
    description: "Groups investigate where the data behind four common AI apps actually comes from, who collected it, and whether the people represented consented — then report to class.",
    tags: ["data", "consent", "privacy", "ethics"],
    uses: 274,
    rating: 4.8,
    verified: true,
    date: "2026-02-14",
  },
  {
    id: "cl-9",
    title: "Sorting Ourselves: How Algorithms Categorize People",
    subject: "Mathematics",
    grade: "9–12",
    duration: "50 min",
    teacher: "Lin Wei",
    school: "Northwest STEM Academy",
    state: "OR",
    aiConcept: "Classification",
    description: "Students experience how classification algorithms work by hand-sorting a dataset, then reflect on the tradeoffs between accuracy and the human cost of errors.",
    tags: ["math", "classification", "privacy"],
    uses: 198,
    rating: 4.6,
    verified: true,
    date: "2026-01-22",
  },
  {
    id: "cl-10",
    title: "Voice Assistants and the Languages They Ignore",
    subject: "World Languages",
    grade: "6–8",
    duration: "45 min",
    teacher: "Fatima Al-Hassan",
    school: "Global Connections Middle",
    state: "TX",
    aiConcept: "Language & AI",
    description: "Students test popular voice assistants in multiple languages and accents, document where they fail, and discuss the linguistic equity implications of AI language models.",
    tags: ["language", "equity", "voice AI", "culture"],
    uses: 143,
    rating: 4.7,
    verified: false,
    date: "2026-03-05",
  },
]
